account_id = "356ac37112b5151a6c8a15d22c091d99"
name = "cf-worker-status-page-pro"
main = "./src/worker/index.ts"
compatibility_flags = [ "streams_enable_constructors" ]
compatibility_date = "2021-09-29"
workers_dev = true
# npx --no -- wrangler kv:namespace create cf-worker-status-page-pro
kv_namespaces = [ { binding = "KV_STORE", id = "89cf5741f34c49f9938eb7422d18e3e8" }, ]

[site]
bucket = "./dist/client"

[dev]
port = 3000

[env.production]
kv_namespaces = [ { binding = "KV_STORE", id = "89cf5741f34c49f9938eb7422d18e3e8" }, ]

[env.production.triggers]
crons = [
  # https://crontab.guru/#*/2_*_*_*_*
  # Check monitors
  "*/10 * * * *",
  # https://crontab.guru/#*/10_*_*_*_*
  # Update remote csv monitors
  "0 0 */1 * *",
]
